version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./dockerify/app/Dockerfile
    ports:
      - '8091:8091'
    tmpfs:
      - /tmp
    volumes:
      - .:/app/code
    depends_on:
      - db
    environment:
      - DEBUG=1
      - BASE_URL=http://localhost
      - POSTGRES_HOST=db
      - POSTGRES_USER=blog-user
      - POSTGRES_DB=blog
      - POSTGRES_PASSWORD=test@123
      - REDIS_HOST=redis

  redis:
    image: redis



  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=blog-user
      - POSTGRES_PASSWORD=test@123
      - POSTGRES_DB=blog
